ALTER TABLE `users`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `events`
  MODIFY COLUMN `id` VARCHAR(36) NOT NULL FIRST;

ALTER TABLE `report`
  MODIFY COLUMN `id` VARCHAR(36) NOT NULL FIRST;
