ALTER TABLE `report`
  MODIFY COLUMN `id` CHAR(36) NOT NULL FIRST,
  MODIFY COLUMN `uploaded_report` LONGTEXT NOT NULL AFTER `id`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `uploaded_report`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`;
