ALTER TABLE `events`
  MODIFY COLUMN `id` CHAR(36) NOT NULL FIRST,
  MODIFY COLUMN `title` VARCHAR(255) NOT NULL AFTER `id`,
  MODIFY COLUMN `description` TEXT NOT NULL AFTER `title`,
  MODIFY COLUMN `date` VARCHAR(10) NOT NULL AFTER `description`,
  MODIFY COLUMN `start_time` VARCHAR(5) NOT NULL AFTER `date`,
  MODIFY COLUMN `end_time` VARCHAR(5) NOT NULL AFTER `start_time`,
  MODIFY COLUMN `status` VARCHAR(50) NOT NULL AFTER `end_time`,
  MODIFY COLUMN `category` VARCHAR(50) NOT NULL AFTER `status`,
  MODIFY COLUMN `user_link` INT NOT NULL AFTER `category`,
  MODIFY COLUMN `event_attendees` JSON NULL AFTER `user_link`,
  MODIFY COLUMN `event_attachments` JSON NULL AFTER `event_attendees`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `event_attachments`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`;
