SET @fk_name := (
  SELECT CONSTRAINT_NAME
  FROM information_schema.KEY_COLUMN_USAGE
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'events'
    AND COLUMN_NAME = 'user_link'
    AND REFERENCED_TABLE_NAME = 'users'
  LIMIT 1
);

SET @drop_fk_sql := IF(
  @fk_name IS NOT NULL,
  CONCAT('ALTER TABLE `events` DROP FOREIGN KEY `', @fk_name, '`'),
  'SELECT 1'
);
PREPARE stmt FROM @drop_fk_sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

ALTER TABLE `users`
  CHANGE COLUMN `ID` `id` INT NOT NULL AUTO_INCREMENT FIRST,
  MODIFY COLUMN `username` VARCHAR(255) NOT NULL AFTER `id`,
  MODIFY COLUMN `password` VARCHAR(255) NOT NULL AFTER `username`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `password`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`,
  MODIFY COLUMN `slug` VARCHAR(255) NOT NULL AFTER `updated_at`,
  MODIFY COLUMN `fulname` VARCHAR(255) NOT NULL AFTER `slug`;

ALTER TABLE `events`
  CHANGE COLUMN `ID` `id` CHAR(36) NOT NULL FIRST,
  MODIFY COLUMN `title` VARCHAR(255) NOT NULL AFTER `id`,
  MODIFY COLUMN `description` VARCHAR(255) NOT NULL DEFAULT '' AFTER `title`,
  MODIFY COLUMN `date` VARCHAR(255) NOT NULL AFTER `description`,
  MODIFY COLUMN `start_time` VARCHAR(255) NOT NULL AFTER `date`,
  MODIFY COLUMN `end_time` VARCHAR(255) NOT NULL AFTER `start_time`,
  MODIFY COLUMN `status` VARCHAR(255) NOT NULL AFTER `end_time`,
  MODIFY COLUMN `category` VARCHAR(255) NOT NULL AFTER `status`,
  MODIFY COLUMN `event_attendees` TEXT NULL AFTER `category`,
  MODIFY COLUMN `event_attachment` TEXT NULL AFTER `event_attendees`,
  MODIFY COLUMN `user_link` INT NOT NULL AFTER `event_attachment`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `user_link`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`;

ALTER TABLE `report`
  CHANGE COLUMN `ID` `id` CHAR(36) NOT NULL FIRST,
  MODIFY COLUMN `uploaded_report` LONGTEXT NOT NULL AFTER `id`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `uploaded_report`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`;

ALTER TABLE `events`
  ADD CONSTRAINT `FK_events_user_link`
  FOREIGN KEY (`user_link`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
