ALTER TABLE `users`
  CHANGE COLUMN `ID` `ID` INT NOT NULL AUTO_INCREMENT FIRST,
  MODIFY COLUMN `username` VARCHAR(255) NOT NULL AFTER `ID`,
  MODIFY COLUMN `password` VARCHAR(255) NOT NULL AFTER `username`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `password`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`,
  MODIFY COLUMN `slug` VARCHAR(255) NOT NULL AFTER `updated_at`,
  MODIFY COLUMN `fulname` VARCHAR(255) NOT NULL AFTER `slug`;

ALTER TABLE `events`
  CHANGE COLUMN `ID` `ID` CHAR(36) NOT NULL FIRST,
  MODIFY COLUMN `title` VARCHAR(255) NOT NULL AFTER `ID`,
  MODIFY COLUMN `description` VARCHAR(255) NOT NULL DEFAULT '' AFTER `title`,
  MODIFY COLUMN `date` VARCHAR(255) NOT NULL AFTER `description`,
  MODIFY COLUMN `start_time` VARCHAR(255) NOT NULL AFTER `date`,
  MODIFY COLUMN `end_time` VARCHAR(255) NOT NULL AFTER `start_time`,
  MODIFY COLUMN `status` VARCHAR(255) NOT NULL AFTER `end_time`,
  MODIFY COLUMN `category` VARCHAR(255) NOT NULL AFTER `status`,
  MODIFY COLUMN `event_attendees` TEXT NULL AFTER `category`,
  MODIFY COLUMN `event_attachment` TEXT NULL AFTER `event_attendees`,
  MODIFY COLUMN `user_link` INT NOT NULL AFTER `event_attachment`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `user_link`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`;

ALTER TABLE `report`
  CHANGE COLUMN `ID` `ID` CHAR(36) NOT NULL FIRST,
  MODIFY COLUMN `uploaded_report` LONGTEXT NOT NULL AFTER `ID`,
  MODIFY COLUMN `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER `uploaded_report`,
  MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER `created_at`;
